###
POST http://localhost:8080/person
Content-Type: application/json

{
  "id": 40000,
  "name": "Alex1"
}

###
PUT http://localhost:8080/person
Content-Type: application/json

{
  "id": 3,
  "name": "Alex1"
}

###
DELETE http://localhost:8080/person/3

###
POST http://localhost:8080/order
Content-Type: application/json

{
  "id": 10,
  "total": 123.45,
  "comment": "test"
}

###
POST http://localhost:8080/order
Content-Type: application/json

{
}